const funFacts = [
    "A shrimp's heart is in its head.",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old and still perfectly good to eat.",
    "Bananas are berries, but strawberries are not.",
    "Octopuses have three hearts.",
    "A day on Venus is longer than a year on Venus.",
    "Wombat poop is cube-shaped.",
    "The Eiffel Tower can grow taller in summer due to heat expansion.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Sloths can hold their breath longer than dolphins.",
    "A jellyfish is 95% water.",
    "Cows have best friends and get stressed when separated.",
    "You can't hum while holding your nose.",
    "Butterflies can taste with their feet.",
    "Water makes different pouring sounds depending on temperature.",
    "A bolt of lightning is five times hotter than the sun.",
    "Humans share about 60% of their DNA with bananas.",
    "A group of flamingos is called a 'flamboyance.'",
    "Scotland has 421 words for 'snow.'",
    "An astronaut's height can increase by 2 inches in space.",
    "The longest hiccuping spree lasted 68 years.",
    "Sharks existed before trees.",
    "There's a species of jellyfish that is biologically immortal.",
    "A sneeze travels about 100 miles per hour.",
    "There's an island in Japan where bunnies outnumber people.",
    "Pineapples take about two years to grow.",
    "A cloud can weigh over a million pounds.",
    "The first oranges weren't orange; they were green.",
    "You blink about 20 times per minute, which is over 10 million times per year.",
    "An octopus has nine brains.",
    "Some turtles can breathe through their butts.",
    "A cockroach can live for weeks without its head.",
    "Polar bears have black skin under their white fur.",
    "A blue whale's heart is as big as a small car.",
    "Elephants can 'hear' with their feet.",
    "There’s a hotel in Sweden made entirely of ice.",
    "Venus is the hottest planet in our solar system, not Mercury.",
    "Goats have rectangular pupils.",
    "A small child could swim through the veins of a blue whale.",
    "The speed of a computer mouse is measured in 'Mickeys'.",
    "The human body contains enough carbon to make about 9000 pencils.",
    "Cats have a third eyelid.",
    "An ant can carry 50 times its body weight.",
    "You can’t fold a piece of paper in half more than 7 times.",
    "Some frogs can freeze solid and survive.",
    "The world's largest desert is actually Antarctica.",
    "The longest wedding veil was longer than 63 football fields.",
    "There are more fake flamingos in the world than real ones.",
    "Bananas glow blue under black light.",
    "A single spaghetti noodle is called a 'spaghetto'.",
    "Horses and cows can sleep standing up.",
    "Apples float because they are 25% air.",
    "An octopus can squeeze through a hole the size of a coin.",
    "Snails can sleep for three years.",
    "A group of owls is called a parliament.",
    "There's a lake in Australia that stays bright pink year-round.",
    "It's impossible to tickle yourself.",
    "The national animal of Scotland is the unicorn.",
    "The world's largest pyramid is in Mexico, not Egypt.",
    "A cat’s purr has healing properties.",
    "A violin bow is typically made from horsehair.",
    "There's a species of fish that can walk on land.",
    "Ketchup was once sold as medicine.",
    "Octopuses can change color in an instant.",
    "There is a town in Norway where the sun doesn’t set for months.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "A group of crows is called a murder.",
    "If you keep a goldfish in the dark, it will lose its color.",
    "The world's quietest room is so silent that you can hear your own heartbeat.",
    "You are taller in the morning than in the evening.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "A shrimp's brain is in its stomach.",
    "The first alarm clock could only ring at 4 a.m.",
    "The inventor of the stethoscope originally rolled up a piece of paper to listen to a heartbeat.",
    "Tigers have striped skin, not just striped fur.",
    "There is no sound in space because there is no air to carry vibrations.",
    "A baby octopus is about the size of a flea when born.",
    "The smell of freshly cut grass is actually a distress signal from the grass.",
];

function generateFact() {
    const randomIndex = Math.floor(Math.random() * funFacts.length);
    document.getElementById("fact-display").textContent = funFacts[randomIndex];
}
